package domain.model;
// Generated 9 nov. 2011 19:39:34 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name="DEPARTMENT"
    ,schema="JULIEN"
)
public class Department  implements java.io.Serializable {


     private String mnemo;
     private Teacher teacher;
     private String label;
     private String diplomasVersion;
     private Set stages = new HashSet(0);

    public Department() {
    }

	
    public Department(String mnemo) {
        this.mnemo = mnemo;
    }
    public Department(String mnemo, Teacher teacher, String label, String diplomasVersion, Set stages) {
       this.mnemo = mnemo;
       this.teacher = teacher;
       this.label = label;
       this.diplomasVersion = diplomasVersion;
       this.stages = stages;
    }
   
     @Id 
    
    @Column(name="MNEMO", unique=true, nullable=false, length=10)
    public String getMnemo() {
        return this.mnemo;
    }
    
    public void setMnemo(String mnemo) {
        this.mnemo = mnemo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PERSON_IN_CHARGE")
    public Teacher getTeacher() {
        return this.teacher;
    }
    
    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }
    
    @Column(name="LABEL", length=200)
    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }
    
    @Column(name="DIPLOMAS_VERSION", length=20)
    public String getDiplomasVersion() {
        return this.diplomasVersion;
    }
    
    public void setDiplomasVersion(String diplomasVersion) {
        this.diplomasVersion = diplomasVersion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="department")
    public Set getStages() {
        return this.stages;
    }
    
    public void setStages(Set stages) {
        this.stages = stages;
    }




}


