package domain.model;
// Generated 9 nov. 2011 19:39:34 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ecue generated by hbm2java
 */
@Entity
@Table(name="ECUE"
    ,schema="JULIEN"
)
public class Ecue  implements java.io.Serializable {


     private String ecueCode;
     private Teacher teacher;
     private Ue ue;
     private String label;
     private BigDecimal semesterNumber;
     private BigDecimal hours;
     private Byte optional;
     private Set marks = new HashSet(0);

    public Ecue() {
    }

	
    public Ecue(String ecueCode) {
        this.ecueCode = ecueCode;
    }
    public Ecue(String ecueCode, Teacher teacher, Ue ue, String label, BigDecimal semesterNumber, BigDecimal hours, Byte optional, Set marks) {
       this.ecueCode = ecueCode;
       this.teacher = teacher;
       this.ue = ue;
       this.label = label;
       this.semesterNumber = semesterNumber;
       this.hours = hours;
       this.optional = optional;
       this.marks = marks;
    }
   
     @Id 
    
    @Column(name="ECUE_CODE", unique=true, nullable=false, length=20)
    public String getEcueCode() {
        return this.ecueCode;
    }
    
    public void setEcueCode(String ecueCode) {
        this.ecueCode = ecueCode;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PERSON_IN_CHARGE")
    public Teacher getTeacher() {
        return this.teacher;
    }
    
    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="UE_CODE")
    public Ue getUe() {
        return this.ue;
    }
    
    public void setUe(Ue ue) {
        this.ue = ue;
    }
    
    @Column(name="LABEL", length=50)
    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }
    
    @Column(name="SEMESTER_NUMBER", precision=22, scale=0)
    public BigDecimal getSemesterNumber() {
        return this.semesterNumber;
    }
    
    public void setSemesterNumber(BigDecimal semesterNumber) {
        this.semesterNumber = semesterNumber;
    }
    
    @Column(name="HOURS", precision=22, scale=0)
    public BigDecimal getHours() {
        return this.hours;
    }
    
    public void setHours(BigDecimal hours) {
        this.hours = hours;
    }
    
    @Column(name="OPTIONAL", precision=2, scale=0)
    public Byte getOptional() {
        return this.optional;
    }
    
    public void setOptional(Byte optional) {
        this.optional = optional;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="ecue")
    public Set getMarks() {
        return this.marks;
    }
    
    public void setMarks(Set marks) {
        this.marks = marks;
    }




}


