package domain.model;
// Generated 9 nov. 2011 19:39:34 by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Mark generated by hbm2java
 */
@Entity
@Table(name="MARK"
    ,schema="JULIEN"
)
public class Mark  implements java.io.Serializable {


     private MarkId id;
     private Student student;
     private Ecue ecue;
     private Byte mark1;
     private Byte mark2;

    public Mark() {
    }

	
    public Mark(MarkId id, Student student, Ecue ecue) {
        this.id = id;
        this.student = student;
        this.ecue = ecue;
    }
    public Mark(MarkId id, Student student, Ecue ecue, Byte mark1, Byte mark2) {
       this.id = id;
       this.student = student;
       this.ecue = ecue;
       this.mark1 = mark1;
       this.mark2 = mark2;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="studentNumber", column=@Column(name="STUDENT_NUMBER", nullable=false, precision=8, scale=0) ), 
        @AttributeOverride(name="ecueCode", column=@Column(name="ECUE_CODE", nullable=false, length=20) ) } )
    public MarkId getId() {
        return this.id;
    }
    
    public void setId(MarkId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STUDENT_NUMBER", nullable=false, insertable=false, updatable=false)
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ECUE_CODE", nullable=false, insertable=false, updatable=false)
    public Ecue getEcue() {
        return this.ecue;
    }
    
    public void setEcue(Ecue ecue) {
        this.ecue = ecue;
    }
    
    @Column(name="MARK1", precision=2, scale=0)
    public Byte getMark1() {
        return this.mark1;
    }
    
    public void setMark1(Byte mark1) {
        this.mark1 = mark1;
    }
    
    @Column(name="MARK2", precision=2, scale=0)
    public Byte getMark2() {
        return this.mark2;
    }
    
    public void setMark2(Byte mark2) {
        this.mark2 = mark2;
    }




}


