package domain.model;
// Generated 9 nov. 2011 19:39:34 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MarkId generated by hbm2java
 */
@Embeddable
public class MarkId  implements java.io.Serializable {


     private int studentNumber;
     private String ecueCode;

    public MarkId() {
    }

    public MarkId(int studentNumber, String ecueCode) {
       this.studentNumber = studentNumber;
       this.ecueCode = ecueCode;
    }
   

    @Column(name="STUDENT_NUMBER", nullable=false, precision=8, scale=0)
    public int getStudentNumber() {
        return this.studentNumber;
    }
    
    public void setStudentNumber(int studentNumber) {
        this.studentNumber = studentNumber;
    }

    @Column(name="ECUE_CODE", nullable=false, length=20)
    public String getEcueCode() {
        return this.ecueCode;
    }
    
    public void setEcueCode(String ecueCode) {
        this.ecueCode = ecueCode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MarkId) ) return false;
		 MarkId castOther = ( MarkId ) other; 
         
		 return (this.getStudentNumber()==castOther.getStudentNumber())
 && ( (this.getEcueCode()==castOther.getEcueCode()) || ( this.getEcueCode()!=null && castOther.getEcueCode()!=null && this.getEcueCode().equals(castOther.getEcueCode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getStudentNumber();
         result = 37 * result + ( getEcueCode() == null ? 0 : this.getEcueCode().hashCode() );
         return result;
   }   


}


