package domain.model;
// Generated 9 nov. 2011 19:39:34 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name="PRODUCTS"
    ,schema="JULIEN"
)
public class Products  implements java.io.Serializable {


     private BigDecimal id;
     private String description;
     private BigDecimal price;

    public Products() {
    }

	
    public Products(BigDecimal id) {
        this.id = id;
    }
    public Products(BigDecimal id, String description, BigDecimal price) {
       this.id = id;
       this.description = description;
       this.price = price;
    }
   
     @Id 
    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    
    @Column(name="DESCRIPTION")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="PRICE", precision=15)
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }




}


