package domain.model;
// Generated 9 nov. 2011 19:39:34 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Semester generated by hbm2java
 */
@Entity
@Table(name="SEMESTER"
    ,schema="JULIEN"
)
public class Semester  implements java.io.Serializable {


     private String semesterCode;
     private Stage stage;
     private String label;
     private BigDecimal optionalUes;
     private Set specificities = new HashSet(0);
     private Set juryPointses = new HashSet(0);
     private Set ues = new HashSet(0);

    public Semester() {
    }

	
    public Semester(String semesterCode) {
        this.semesterCode = semesterCode;
    }
    public Semester(String semesterCode, Stage stage, String label, BigDecimal optionalUes, Set specificities, Set juryPointses, Set ues) {
       this.semesterCode = semesterCode;
       this.stage = stage;
       this.label = label;
       this.optionalUes = optionalUes;
       this.specificities = specificities;
       this.juryPointses = juryPointses;
       this.ues = ues;
    }
   
     @Id 
    
    @Column(name="SEMESTER_CODE", unique=true, nullable=false, length=10)
    public String getSemesterCode() {
        return this.semesterCode;
    }
    
    public void setSemesterCode(String semesterCode) {
        this.semesterCode = semesterCode;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="DEPARTMENT_MNEMO", referencedColumnName="DEPARTMENT_MNEMO"), 
        @JoinColumn(name="STAGE_NUMBER", referencedColumnName="STAGE_NUMBER") } )
    public Stage getStage() {
        return this.stage;
    }
    
    public void setStage(Stage stage) {
        this.stage = stage;
    }
    
    @Column(name="LABEL", length=20)
    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }
    
    @Column(name="OPTIONAL_UES", precision=22, scale=0)
    public BigDecimal getOptionalUes() {
        return this.optionalUes;
    }
    
    public void setOptionalUes(BigDecimal optionalUes) {
        this.optionalUes = optionalUes;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="semester")
    public Set getSpecificities() {
        return this.specificities;
    }
    
    public void setSpecificities(Set specificities) {
        this.specificities = specificities;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="semester")
    public Set getJuryPointses() {
        return this.juryPointses;
    }
    
    public void setJuryPointses(Set juryPointses) {
        this.juryPointses = juryPointses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="semester")
    public Set getUes() {
        return this.ues;
    }
    
    public void setUes(Set ues) {
        this.ues = ues;
    }




}


