package domain.model;
// Generated 9 nov. 2011 19:39:34 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SpecificityId generated by hbm2java
 */
@Embeddable
public class SpecificityId  implements java.io.Serializable {


     private int studentNumber;
     private String semesterCode;

    public SpecificityId() {
    }

    public SpecificityId(int studentNumber, String semesterCode) {
       this.studentNumber = studentNumber;
       this.semesterCode = semesterCode;
    }
   

    @Column(name="STUDENT_NUMBER", nullable=false, precision=8, scale=0)
    public int getStudentNumber() {
        return this.studentNumber;
    }
    
    public void setStudentNumber(int studentNumber) {
        this.studentNumber = studentNumber;
    }

    @Column(name="SEMESTER_CODE", nullable=false, length=10)
    public String getSemesterCode() {
        return this.semesterCode;
    }
    
    public void setSemesterCode(String semesterCode) {
        this.semesterCode = semesterCode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SpecificityId) ) return false;
		 SpecificityId castOther = ( SpecificityId ) other; 
         
		 return (this.getStudentNumber()==castOther.getStudentNumber())
 && ( (this.getSemesterCode()==castOther.getSemesterCode()) || ( this.getSemesterCode()!=null && castOther.getSemesterCode()!=null && this.getSemesterCode().equals(castOther.getSemesterCode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getStudentNumber();
         result = 37 * result + ( getSemesterCode() == null ? 0 : this.getSemesterCode().hashCode() );
         return result;
   }   


}


