package domain.model;
// Generated 9 nov. 2011 19:39:34 by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Specificity generated by hbm2java
 */
@Entity
@Table(name="SPECIFICITY"
    ,schema="JULIEN"
)
public class Specificity  implements java.io.Serializable {


     private SpecificityId id;
     private Student student;
     private Semester semester;
     private Byte average;
     private String label;

    public Specificity() {
    }

	
    public Specificity(SpecificityId id, Student student, Semester semester) {
        this.id = id;
        this.student = student;
        this.semester = semester;
    }
    public Specificity(SpecificityId id, Student student, Semester semester, Byte average, String label) {
       this.id = id;
       this.student = student;
       this.semester = semester;
       this.average = average;
       this.label = label;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="studentNumber", column=@Column(name="STUDENT_NUMBER", nullable=false, precision=8, scale=0) ), 
        @AttributeOverride(name="semesterCode", column=@Column(name="SEMESTER_CODE", nullable=false, length=10) ) } )
    public SpecificityId getId() {
        return this.id;
    }
    
    public void setId(SpecificityId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STUDENT_NUMBER", nullable=false, insertable=false, updatable=false)
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SEMESTER_CODE", nullable=false, insertable=false, updatable=false)
    public Semester getSemester() {
        return this.semester;
    }
    
    public void setSemester(Semester semester) {
        this.semester = semester;
    }
    
    @Column(name="AVERAGE", precision=2, scale=0)
    public Byte getAverage() {
        return this.average;
    }
    
    public void setAverage(Byte average) {
        this.average = average;
    }
    
    @Column(name="LABEL", length=20)
    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }




}


