package domain.model;
// Generated 9 nov. 2011 19:39:34 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Stage generated by hbm2java
 */
@Entity
@Table(name="STAGE"
    ,schema="JULIEN"
)
public class Stage  implements java.io.Serializable {


     private StageId id;
     private Department department;
     private Teacher teacher;
     private Set students = new HashSet(0);
     private Set semesters = new HashSet(0);

    public Stage() {
    }

	
    public Stage(StageId id, Department department) {
        this.id = id;
        this.department = department;
    }
    public Stage(StageId id, Department department, Teacher teacher, Set students, Set semesters) {
       this.id = id;
       this.department = department;
       this.teacher = teacher;
       this.students = students;
       this.semesters = semesters;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="departmentMnemo", column=@Column(name="DEPARTMENT_MNEMO", nullable=false, length=10) ), 
        @AttributeOverride(name="stageNumber", column=@Column(name="STAGE_NUMBER", nullable=false, precision=22, scale=0) ) } )
    public StageId getId() {
        return this.id;
    }
    
    public void setId(StageId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DEPARTMENT_MNEMO", nullable=false, insertable=false, updatable=false)
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PERSON_IN_CHARGE")
    public Teacher getTeacher() {
        return this.teacher;
    }
    
    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="stage")
    public Set getStudents() {
        return this.students;
    }
    
    public void setStudents(Set students) {
        this.students = students;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="stage")
    public Set getSemesters() {
        return this.semesters;
    }
    
    public void setSemesters(Set semesters) {
        this.semesters = semesters;
    }




}


