package domain.model;
// Generated 9 nov. 2011 19:39:34 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name="STUDENT"
    ,schema="JULIEN"
)
public class Student  implements java.io.Serializable {


     private int studentNumber;
     private Nationality nationality;
     private Stage stage;
     private Origin origin;
     private String lastname;
     private String firstname;
     private String sex;
     private String email;
     private String ineNumber;
     private Short toeicScore;
     private Double juryPoints;
     private String juryComment;
     private String password;
     private Set specificities = new HashSet(0);
     private Set ues = new HashSet(0);
     private Set statuses = new HashSet(0);
     private Set marks = new HashSet(0);
     private Set juryPointses = new HashSet(0);
     private Set ues_1 = new HashSet(0);
     private Set ues_2 = new HashSet(0);

    public Student() {
    }

	
    public Student(int studentNumber) {
        this.studentNumber = studentNumber;
    }
    public Student(int studentNumber, Nationality nationality, Stage stage, Origin origin, String lastname, String firstname, String sex, String email, String ineNumber, Short toeicScore, Double juryPoints, String juryComment, String password, Set specificities, Set ues, Set statuses, Set marks, Set juryPointses, Set ues_1, Set ues_2) {
       this.studentNumber = studentNumber;
       this.nationality = nationality;
       this.stage = stage;
       this.origin = origin;
       this.lastname = lastname;
       this.firstname = firstname;
       this.sex = sex;
       this.email = email;
       this.ineNumber = ineNumber;
       this.toeicScore = toeicScore;
       this.juryPoints = juryPoints;
       this.juryComment = juryComment;
       this.password = password;
       this.specificities = specificities;
       this.ues = ues;
       this.statuses = statuses;
       this.marks = marks;
       this.juryPointses = juryPointses;
       this.ues_1 = ues_1;
       this.ues_2 = ues_2;
    }
   
     @Id 
    
    @Column(name="STUDENT_NUMBER", unique=true, nullable=false, precision=8, scale=0)
    public int getStudentNumber() {
        return this.studentNumber;
    }
    
    public void setStudentNumber(int studentNumber) {
        this.studentNumber = studentNumber;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NATIONALITY_ID")
    public Nationality getNationality() {
        return this.nationality;
    }
    
    public void setNationality(Nationality nationality) {
        this.nationality = nationality;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="DEPARTMENT_MNEMO", referencedColumnName="DEPARTMENT_MNEMO"), 
        @JoinColumn(name="STAGE_NUMBER", referencedColumnName="STAGE_NUMBER") } )
    public Stage getStage() {
        return this.stage;
    }
    
    public void setStage(Stage stage) {
        this.stage = stage;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ORIGIN_ID")
    public Origin getOrigin() {
        return this.origin;
    }
    
    public void setOrigin(Origin origin) {
        this.origin = origin;
    }
    
    @Column(name="LASTNAME", length=40)
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    
    @Column(name="FIRSTNAME", length=40)
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    
    @Column(name="SEX", length=2)
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    
    @Column(name="EMAIL", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="INE_NUMBER", length=10)
    public String getIneNumber() {
        return this.ineNumber;
    }
    
    public void setIneNumber(String ineNumber) {
        this.ineNumber = ineNumber;
    }
    
    @Column(name="TOEIC_SCORE", precision=3, scale=0)
    public Short getToeicScore() {
        return this.toeicScore;
    }
    
    public void setToeicScore(Short toeicScore) {
        this.toeicScore = toeicScore;
    }
    
    @Column(name="JURY_POINTS", precision=126, scale=0)
    public Double getJuryPoints() {
        return this.juryPoints;
    }
    
    public void setJuryPoints(Double juryPoints) {
        this.juryPoints = juryPoints;
    }
    
    @Column(name="JURY_COMMENT", length=200)
    public String getJuryComment() {
        return this.juryComment;
    }
    
    public void setJuryComment(String juryComment) {
        this.juryComment = juryComment;
    }
    
    @Column(name="PASSWORD", length=20)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="student")
    public Set getSpecificities() {
        return this.specificities;
    }
    
    public void setSpecificities(Set specificities) {
        this.specificities = specificities;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="STUDENT_OPTIONAL_UES", schema="JULIEN", joinColumns = { 
        @JoinColumn(name="STUDENT_NUMBER", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="UE_CODE", nullable=false, updatable=false) })
    public Set getUes() {
        return this.ues;
    }
    
    public void setUes(Set ues) {
        this.ues = ues;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="STUDENT_STATUS", schema="JULIEN", joinColumns = { 
        @JoinColumn(name="STUDENT_NUMBER", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="STATUS_ID", nullable=false, updatable=false) })
    public Set getStatuses() {
        return this.statuses;
    }
    
    public void setStatuses(Set statuses) {
        this.statuses = statuses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="student")
    public Set getMarks() {
        return this.marks;
    }
    
    public void setMarks(Set marks) {
        this.marks = marks;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="student")
    public Set getJuryPointses() {
        return this.juryPointses;
    }
    
    public void setJuryPointses(Set juryPointses) {
        this.juryPointses = juryPointses;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="VAE", schema="JULIEN", joinColumns = { 
        @JoinColumn(name="STUDENT_NUMBER", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="UE_CODE", nullable=false, updatable=false) })
    public Set getUes_1() {
        return this.ues_1;
    }
    
    public void setUes_1(Set ues_1) {
        this.ues_1 = ues_1;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="APDJ", schema="JULIEN", joinColumns = { 
        @JoinColumn(name="STUDENT_NUMBER", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="UE_CODE", nullable=false, updatable=false) })
    public Set getUes_2() {
        return this.ues_2;
    }
    
    public void setUes_2(Set ues_2) {
        this.ues_2 = ues_2;
    }




}


