package domain.model;
// Generated 9 nov. 2011 19:39:34 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ue generated by hbm2java
 */
@Entity
@Table(name="UE"
    ,schema="JULIEN"
)
public class Ue  implements java.io.Serializable {


     private String ueCode;
     private Teacher teacher;
     private Semester semester;
     private String label;
     private BigDecimal ects;
     private Byte optional;
     private Set students = new HashSet(0);
     private Set students_1 = new HashSet(0);
     private Set ecues = new HashSet(0);
     private Set students_2 = new HashSet(0);

    public Ue() {
    }

	
    public Ue(String ueCode) {
        this.ueCode = ueCode;
    }
    public Ue(String ueCode, Teacher teacher, Semester semester, String label, BigDecimal ects, Byte optional, Set students, Set students_1, Set ecues, Set students_2) {
       this.ueCode = ueCode;
       this.teacher = teacher;
       this.semester = semester;
       this.label = label;
       this.ects = ects;
       this.optional = optional;
       this.students = students;
       this.students_1 = students_1;
       this.ecues = ecues;
       this.students_2 = students_2;
    }
   
     @Id 
    
    @Column(name="UE_CODE", unique=true, nullable=false, length=20)
    public String getUeCode() {
        return this.ueCode;
    }
    
    public void setUeCode(String ueCode) {
        this.ueCode = ueCode;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PERSON_IN_CHARGE")
    public Teacher getTeacher() {
        return this.teacher;
    }
    
    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SEMESTER_CODE")
    public Semester getSemester() {
        return this.semester;
    }
    
    public void setSemester(Semester semester) {
        this.semester = semester;
    }
    
    @Column(name="LABEL", length=30)
    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }
    
    @Column(name="ECTS", precision=22, scale=0)
    public BigDecimal getEcts() {
        return this.ects;
    }
    
    public void setEcts(BigDecimal ects) {
        this.ects = ects;
    }
    
    @Column(name="OPTIONAL", precision=2, scale=0)
    public Byte getOptional() {
        return this.optional;
    }
    
    public void setOptional(Byte optional) {
        this.optional = optional;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="ues")
    public Set getStudents() {
        return this.students;
    }
    
    public void setStudents(Set students) {
        this.students = students;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="ues")
    public Set getStudents_1() {
        return this.students_1;
    }
    
    public void setStudents_1(Set students_1) {
        this.students_1 = students_1;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="ue")
    public Set getEcues() {
        return this.ecues;
    }
    
    public void setEcues(Set ecues) {
        this.ecues = ecues;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="ues")
    public Set getStudents_2() {
        return this.students_2;
    }
    
    public void setStudents_2(Set students_2) {
        this.students_2 = students_2;
    }




}


