package domain.model;
// Generated 8 nov. 2011 21:56:17 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="USERS"
    ,schema="Tyrabius"
)
public class Users  implements java.io.Serializable {


     private short idUser;
     private String loginUser;
     private String mdpUser;

    public Users() {
    }

	
    public Users(short idUser) {
        this.idUser = idUser;
    }
    public Users(short idUser, String loginUser, String mdpUser) {
       this.idUser = idUser;
       this.loginUser = loginUser;
       this.mdpUser = mdpUser;
    }
   
     @Id 
    
    @Column(name="ID_USER", unique=true, nullable=false, precision=4, scale=0)
    public short getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(short idUser) {
        this.idUser = idUser;
    }
    
    @Column(name="LOGIN_USER", length=20)
    public String getLoginUser() {
        return this.loginUser;
    }
    
    public void setLoginUser(String loginUser) {
        this.loginUser = loginUser;
    }
    
    @Column(name="MDP_USER", length=20)
    public String getMdpUser() {
        return this.mdpUser;
    }
    
    public void setMdpUser(String mdpUser) {
        this.mdpUser = mdpUser;
    }




}


