package POJO;
// Generated 7 nov. 2011 15:18:10 by Hibernate Tools 3.2.1.GA



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private short idUser;
     private String loginUser;
     private String mdpUser;

    public User() {
    }

	
    public User(short idUser) {
        this.idUser = idUser;
    }
    public User(short idUser, String loginUser, String mdpUser) {
       this.idUser = idUser;
       this.loginUser = loginUser;
       this.mdpUser = mdpUser;
    }
   
    public short getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(short idUser) {
        this.idUser = idUser;
    }
    public String getLoginUser() {
        return this.loginUser;
    }
    
    public void setLoginUser(String loginUser) {
        this.loginUser = loginUser;
    }
    public String getMdpUser() {
        return this.mdpUser;
    }
    
    public void setMdpUser(String mdpUser) {
        this.mdpUser = mdpUser;
    }




}


