package POJO;
// Generated 2 nov. 2011 17:30:31 by Hibernate Tools 3.2.1.GA



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private int idUser;
     private String loginUser;
     private String passwordUser;

    public Users() {
    }

	
    public Users(int idUser) {
        this.idUser = idUser;
    }
    public Users(int idUser, String loginUser, String passwordUser) {
       this.idUser = idUser;
       this.loginUser = loginUser;
       this.passwordUser = passwordUser;
    }
   
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }
    public String getLoginUser() {
        return this.loginUser;
    }
    
    public void setLoginUser(String loginUser) {
        this.loginUser = loginUser;
    }
    public String getPasswordUser() {
        return this.passwordUser;
    }
    
    public void setPasswordUser(String passwordUser) {
        this.passwordUser = passwordUser;
    }




}


